def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activity_logs_activity_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_activity_logs_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('activity_logs_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_admins_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('admins_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Administrators extending users.'
    )

    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_conversations_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('ai_conversations_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Conversations with the AI assistant.'
    )

    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_messages_conversation_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_ai_messages_sender'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('ai_messages_conversation_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'ai_conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ai_recommendations_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('ai_recommendations_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('application_settings_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_appointments_professional_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('appointments_client_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('appointments_professional_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_logs_created_at'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_audit_logs_entity_type_entity_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_audit_logs_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('audit_logs_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Audit trail for administrative actions.'
    )

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clients_assigned_professional_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_clients_invitation_token'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_clients_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('clients_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('clients_assigned_professional_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'professionals', ['assigned_professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Clients extending users, linked to professionals via invitation.'
    )

    with op.batch_alter_table('condition_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_condition_recommendations_condition_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('condition_recommendations_condition_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'health_conditions', ['condition_id'], ['id'])

    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_contact_messages_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_contact_messages_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('contact_messages_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_email_verification_tokens_token'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_email_verification_tokens_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('email_verification_tokens_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_files_file_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_files_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('files_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_foods_calories'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_foods_category_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_foods_name'), if_exists=True)
        batch_op.create_index('idx_foods_source_source_id', ['source', 'source_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('foods_category_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'food_categories', ['category_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Food composition database with nutritional values.'
    )

    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_goal_progress_goal_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_goal_progress_goal_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_goal_progress_progress_date'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('goal_progress_goal_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'goal_tracker', ['goal_id'], ['id'])

    with op.batch_alter_table('goal_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_goal_tracker_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_goal_tracker_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('goal_tracker_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='User goals for nutrition, fitness, weight.'
    )

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_invoices_payment_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_invoices_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('invoices_payment_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('invoices_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'payments', ['payment_id'], ['id'])

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_login_history_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('login_history_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_meal_plans_client_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_meal_plans_created_by'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_meal_plans_date_range'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_meal_plans_professional_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('fk_meal_plans_created_by'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('meal_plans_professional_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('meal_plans_client_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('fk_meal_plans_client'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('fk_meal_plans_professional'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Meal plans created for clients by professionals or AI.'
    )
        batch_op.drop_column('status')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', name='meal_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_meals_meal_plan_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_meals_recipe_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_meals_scheduled_date'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('meals_recipe_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('meals_meal_plan_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'meal_plans', ['meal_plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notification_preferences_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_is_read'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_notifications_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='User notifications.'
    )

    with op.batch_alter_table('nutriscan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_nutriscan_barcode'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_nutriscan_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('nutriscan_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Scanned food labels with AI analysis.'
    )

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_expires_at'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_token'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_password_reset_tokens_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('password_reset_tokens_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::payment_status"))
        batch_op.drop_index(batch_op.f('idx_payments_subscription_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_payments_transaction_reference'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_payments_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('payments_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('payments_subscription_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'user_subscriptions', ['subscription_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('professional_category_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('professional_category_assignments_category_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('professional_category_assignments_professional_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'professional_categories', ['category_id'], ['id'])

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.alter_column('approval_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='professional_approval_status'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::professional_approval_status"))
        batch_op.drop_index(batch_op.f('idx_professionals_approval_rating'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_professionals_approval_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_professionals_license_number'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_professionals_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('fk_professionals_subscription_plan'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('professionals_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'subscription_plans', ['subscription_plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Professionals extending users with approval and subscription.'
    )

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_recipe_ingredients_food_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_recipe_ingredients_recipe_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('recipe_ingredients_food_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('recipe_ingredients_recipe_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'foods', ['food_id'], ['id'])
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_recipe_steps_recipe_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_recipe_steps_unique_step'), if_exists=True)
        batch_op.create_unique_constraint('idx_recipe_steps_unique_step', ['recipe_id', 'step_number'])
        batch_op.drop_constraint(batch_op.f('recipe_steps_recipe_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=postgresql.ENUM('breakfast', 'lunch', 'dinner', 'snack', name='meal_type'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_level'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_recipes_created_by'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_recipes_meal_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_recipes_title'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('recipes_created_by_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Recipes with ingredients and steps.'
    )

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_token'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_refresh_tokens_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('refresh_tokens_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('professional_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_reports_professional_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_reports_report_type'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_reports_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('reports_client_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('reports_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('reports_professional_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sessions_session_token'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_sessions_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('sessions_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shopping_items_food_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_shopping_items_shopping_list_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('shopping_items_food_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('shopping_items_shopping_list_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'shopping_lists', ['shopping_list_id'], ['id'])
        batch_op.create_foreign_key(None, 'foods', ['food_id'], ['id'])

    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shopping_lists_client_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_shopping_lists_meal_plan_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('shopping_lists_client_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('shopping_lists_meal_plan_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'meal_plans', ['meal_plan_id'], ['id'])

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.alter_column('billing_cycle',
               existing_type=postgresql.ENUM('monthly', 'quarterly', 'yearly', name='billing_cycle'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'monthly'::billing_cycle"))
        batch_op.drop_index(batch_op.f('idx_subscription_plans_name'), if_exists=True)
        batch_op.drop_column('target_role')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_system_settings_key'), if_exists=True)

    with op.batch_alter_table('user_food_restrictions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_food_restrictions_restriction_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('user_food_restrictions_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'food_restrictions', ['restriction_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_health_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_health_conditions_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.drop_constraint(batch_op.f('user_health_conditions_condition_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'health_conditions', ['condition_id'], ['id'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('lifestyle',
               existing_type=postgresql.ENUM('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active', name='lifestyle'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('diet_preference',
               existing_type=postgresql.ENUM('omnivore', 'vegetarian', 'vegan', 'pescatarian', 'keto', 'paleo', 'gluten_free', 'dairy_free', 'low_carb', 'other', name='diet_preference'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_user_profiles_bmi'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_user_profiles_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('user_profiles_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Extended profile information for users.'
    )

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('active', 'expired', 'canceled', 'pending', name='subscription_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::subscription_status"))
        batch_op.drop_index(batch_op.f('idx_user_subscriptions_plan_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_user_subscriptions_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_user_subscriptions_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('user_subscriptions_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_weekly_plans', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_user_weekly_plans_user_id'), if_exists=True)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint(batch_op.f('user_weekly_plans_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'professional', 'client', 'admin', name='user_role'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('active', 'inactive', 'suspended', 'pending_verification', name='account_status'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_verification'::account_status"))
        batch_op.drop_index(batch_op.f('idx_users_email'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_users_role'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_users_role_active'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_users_status'), if_exists=True)
        batch_op.drop_table_comment(
        existing_comment='Core user accounts with authentication and role.'
    )

    with op.batch_alter_table('water_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_water_logs_log_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_water_logs_user_date'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_water_logs_user_id'), if_exists=True)
        batch_op.drop_constraint(batch_op.f('water_logs_user_id_fkey'), type_='foreignkey', if_exists=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Daily water intake tracking.'
    )

    # ### end Alembic commands ###
